use_frameworks!

target 'GroupedColorPicker_Example' do
  pod 'GroupedColorPicker', :path => '../'
  pod 'SwiftLint'

  target 'GroupedColorPicker_Tests' do
    inherit! :search_paths

    
  end
end
